---
- block:
  - name: create server
    os_server:
      name: "{{ inventory_hostname }}"
      image: "{{ os_server.image }}"
      availability_zone: "{{ os_server.az }}"
      flavor: "{{ os_server.flavor }}"
      network: "{{ os_server.network }}"
      auto_ip: "{{ os_server.attach_floating_ip }}"
      delete_fip: yes
      security_groups: "{{ os_server.security_groups }}"
      key_name: "{{ os_server.key_pair }}"
      state: "{{ os_server.state }}"

  - block:
    - name: get facts of server
      os_server_facts:
        server: "{{ inventory_hostname }}"

    - name: wait for port being up
      wait_for:
        host: "{{ openstack_servers.0.public_v4 }}"
        port: "{{ ansible_port | default(ansible_ssh_port) | default(22)}}"
        state: started
    when: os_server.state == "present"
  delegate_to: 127.0.0.1
  environment:
    OS_PROJECT_DOMAIN_NAME: "{{ OS_PROJECT_DOMAIN_NAME }}"
    OS_USER_DOMAIN_NAME: "{{ OS_USER_DOMAIN_NAME }}"
    OS_PROJECT_NAME: "{{ OS_PROJECT_NAME }}"
    OS_USERNAME: "{{ OS_USERNAME }}"
    OS_PASSWORD: "{{ OS_PASSWORD }}"
    OS_AUTH_URL: "{{ OS_AUTH_URL }}"
    OS_IDENTITY_API_VERSION: "{{ OS_IDENTITY_API_VERSION }}"
    OS_IMAGE_API_VERSION: "{{ OS_IMAGE_API_VERSION }}"
