---
- block:
  - name: manage server
    os_server:
      name: "{{ inventory_hostname }}"
      image: "{{ openstack_instance.image }}"
      availability_zone: "{{ openstack_instance.az }}"
      flavor: "{{ openstack_instance.flavor }}"
      network: "{{ openstack_instance.network }}"
      auto_ip: "{{ openstack_instance.attach_floating_ip }}"
      delete_fip: yes
      security_groups: "{{ openstack_instance.security_groups }}"
      key_name: "{{ openstack_instance.key_pair }}"
      meta: "{{ openstack_instance.metadata | default(omit) }}"
      state: "{{ openstack_instance.state }}"

  - block:
    - name: get facts of server
      os_server_facts:
        server: "{{ inventory_hostname }}"

    - name: wait for port being up
      wait_for:
        host: "{{ openstack_servers.0.public_v4 }}"
        port: "{{ ansible_port | default(ansible_ssh_port) | default(22)}}"
        state: started
    when: openstack_instance.state == "present"
  delegate_to: 127.0.0.1
  environment:
    OS_PROJECT_DOMAIN_NAME: "{{ OS_PROJECT_DOMAIN_NAME }}"
    OS_USER_DOMAIN_NAME: "{{ OS_USER_DOMAIN_NAME }}"
    OS_PROJECT_NAME: "{{ OS_PROJECT_NAME }}"
    OS_USERNAME: "{{ OS_USERNAME }}"
    OS_PASSWORD: "{{ OS_PASSWORD }}"
    OS_AUTH_URL: "{{ OS_AUTH_URL }}"
    OS_IDENTITY_API_VERSION: "{{ OS_IDENTITY_API_VERSION }}"
    OS_IMAGE_API_VERSION: "{{ OS_IMAGE_API_VERSION }}"
